spring:
  jpa:
    hibernate:
      ddl-auto: none # ???? ??? ?? ??
    properties:
      hibernate:
        format_sql: true
    show-sql: true # SQL ?? ??
  profiles:
    active: local # ?? ??? ???? (test, local ? ??)
logging:
  level:
    org.hibernate.SQL: debug # SQL ?? ??

