spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 스키마 자동 업데이트 (운영에서는 사용 금지)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true # Flyway를 사용하는 경우 활성화
